version: "3.9"

services:
  # -------------------------
  # PostgreSQL Database
  # -------------------------
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a!23456789
      POSTGRES_DB: ECommerceDB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------------
  # Backend API (.NET)
  # -------------------------
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    ports:
      - "5090:5090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5090
      - ConnectionStrings__DefaultConnection=Host=db;Database=ECommerceDB;Username=postgres;Password=a!23456789;Port=5432;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ecommerce-network
    restart: unless-stopped

  # -------------------------
  # Frontend (React + Vite)
  # -------------------------
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ecommerce-network
    environment:
      - VITE_API_URL=http://localhost:5090
    restart: unless-stopped

# -------------------------
# Volumes
# -------------------------
volumes:
  db-data:
    driver: local

# -------------------------
# Networks
# -------------------------
networks:
  ecommerce-network:
    driver: bridge
