version: "3.9"

services:
  # -------------------------
  # PostgreSQL Database
  # -------------------------
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a!23456789
      POSTGRES_DB: ECommerceDB
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./Backend/init-db:/docker-entrypoint-initdb.d